lnguage: python
python:
  - "3.5"
# command to install dependencies
install: "sudo pip install -r requirements.txt"
# command to run tests
script: python manage.py test functional_tests --liveserver=ec2-52-78-45-29.ap-northeast-2.compute.amazonaws.com 
sudo: required
